<?php

namespace SchoolBundle\Repository;

/**
 * studentInClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentInClassRepository extends \Doctrine\ORM\EntityRepository
{
}
