<?php

namespace SchoolBundle\Repository;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends \Doctrine\ORM\EntityRepository
{
	public function getStudentByGender($gender){
		$student = $this->getEntityManager()->createQuery('
			SELECT s FROM SchoolBundle:Student s
			WHERE s.gender = :gender
		')->setParameter('gender', $gender)->getResult();

		return $student;
	}
}
